### ISSUE TITLE
I have to run following command to show chat widget on local host!chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security

### ISSUE THREAD

**Issue by iampanthera** [Alexmhack/Django-Rasa-Bot#15]

**Comment by iampanthera** [comment]
![issue](https://user-images.githubusercontent.com/39412407/70863362-38037800-1f69-11ea-848b-e6b57dbe2bd7.PNG)
if i donot open google without disabling security, following error occur
-----------------------------------------------------------------------------
Access to XMLHttpRequest at 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=My9gh-W' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Alexmhack** [comment]
There are some issues regarding the CORS with rasa, checkout some other issues on this repo, see if they solve your problem.
