### ISSUE TITLE
ModuleNotFoundError: No module named 'decouple'

### ISSUE THREAD

**Issue by amab8901** [Alexmhack/Django-Rasa-Bot#17]
I'm doing a Django project. I'm in my settings.py file. I have done `pip install django-decouple` in my local environment (env). So I insert `from decouple import config`. I run the settings.py file. 

Here's the console output:
`[Running] python -u "/home/amab/VScode Projects/Django Projects/commercial/commercial/settings.py"
Traceback (most recent call last):
  File "/home/amab/VScode Projects/Django Projects/commercial/commercial/settings.py", line 148, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'

[Done] exited with code=1 in 0.042 seconds`

I searched the internet, tried every solution propsed on all the different websites I could find. Nothing works. How do I make this work?

**Comment by Alexmhack** [comment]
You can install decouple using `pip install python-decouple`
