### ISSUE TITLE
Bot stops when can't find answer

### ISSUE THREAD

**Issue by SujanBal** [Alexmhack/Django-Rasa-Bot#7]
At first, it reply's to known questions but when it can't find an answer, it doesn't reply and after that, it won't reply to known questions too. Can u please have a look this? And I want bot to message me first like a 'welcome' message, can u please help me with this too?

**Comment by Alexmhack** [comment]
[Fallback Actions](https://rasa.com/docs/core/fallbacks/#fallback-actions) in rasa docs solves your first problem and [Forum thread](https://forum.rasa.com/t/default-welcome-message/4099) on rasa community form and many other questions are posted related to your second problem.

**I send a message to invoke an intent like `greet` to rasa server when the html page loads using javascript** or you can use the rasa-webchat [property](https://github.com/mrbot-ai/rasa-webchat#in-a-script-tag) `initPayload: "/get_started",` for welcome message.

**Comment by SujanBal** [comment]
Hey Alexmhack, I literally didn't understand that. I'm very very new to this topic but had to make a chatbot for some stupid project undesirably. Can you please update the code for the welcome message, i would really appreciate your help. 
p.s. i would again appreciate if you could provide me your gmail or something, i need to ask you so many things regarding this project. Thank you.

**Comment by Alexmhack** [comment]
**I work on Github daily and github notifies of the conversations happening in the repository issues so will read your questions and try my best to solve it.**

I will update the code for welcome message and the default message on fallback cases of the bot in few hours.

**Comment by SujanBal** [comment]
Hey Alexmhack, so sorry to ask again but I want to connect this chatbot with database. I have a sqlyog database and i want to access that database when talking with a bot e.g., when user gives his username and password which is saved in the database, then the bot has to give his information like name and other things, whatever the user asks. Is this possible? If it is, I would really appreciate your help. Thank you so much.

**Comment by Alexmhack** [comment]
For keeping things simpler you don't need to have a database for storing data, you can create [Rasa Core Actions ](https://rasa.com/docs/core/run-code-in-custom-actions/#custom-actions-written-in-python) and simply store the data in google spreadsheet or email the data to yourself, all of this just using python.

The official sample Chatbot on the Rasa Website itself uses the google spreadsheet to store customer name and email for customer support, you can find its code [here](https://github.com/RasaHQ/rasa-demo).

For your project I think you need to give some time, google things, look on stackoverflow about Python and Rasa Core & Nlu for creating a fully functional and efficient Chatbot, try learning from some nice tutorials on google about the thing you are making.

**Comment by SujanBal** [comment]
Hey @Alexmhack, can u please update the project with one custom action/using slots, I literally didn't understand that and couldn't implement it on my project. I would really appreciate your help. Thank you.

**Comment by Alexmhack** [comment]
**I have many repositories based on Rasa. Checkout [Rasa Tutorial](https://github.com/Alexmhack/rasa_tutorial/tree/master/core_apis).**

**Comment by SujanBal** [comment]
I did the same but I could only run that actions.py file in cmd and couldn't figure out how to show actions in UI. So, i was wondering if you could update those files with django, it would be a great help. Thank you. 
p.s. you were the only one answering my questions and I have only 10 days to submit this project so I need to get this done as soon as possible. So, I would really appreciate if you help me out. Thank you.

**Comment by Alexmhack** [comment]
Updated the repo, run the custom actions in another cmd with the command given below from the folder where the actions.py file is located, in current repo in **rasachat**.

After making necessary changes in the domain.yml file you need to retrain the model also.

`pip install rasa_core_sdk`

`python -m rasa_core_sdk.endpoint --actions actions`

Refer [docs](https://rasa.com/docs/core/run-code-in-custom-actions/#custom-actions-written-in-python) for more details.

**Comment by SujanBal** [comment]
Hey @Alexmhack , I did changes in nlu.md, stories.md and domain.yml to create action but it doesn't work at all. I don't know where's the mistake so can you please make changes in nlu.md and stories.md files and check whether it runs or not and update the files. Also, when i try to run endpoints.yml, the chat is shown in cmd but i want it on django UI. Thank you. Hoping to hear from you soon.
